---
###
### Prometheus RBAC
###
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.global.namespace}}-{{.Values.name}}
  labels:
    {{.Values.global.controllerComponentLabel}}: prometheus
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Values.global.namespace}}-{{.Values.name}}
  labels:
    {{.Values.global.controllerComponentLabel}}: prometheus
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Values.global.namespace}}-{{.Values.name}}
subjects:
- kind: ServiceAccount
  name: {{.Values.name}}
  namespace: {{.Values.global.namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: prometheus
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
